### ISSUE TITLE
Load Convrot Dit node not working with comfy kitchen 0.2.35 (Comfy 0.37.0)

### ISSUE THREAD

**Issue by zpc-git** [wjie98/comfyui-turing-utils#1]
[INFO] [Turing/quantization] Registered scoped sm75+ operator backend: name=turing_utils_sm75 operators=convrot_w4a4_linear,int8_linear,w4a8_int8_linear global_priority=unchanged
[ERROR] !!! Exception during processing !!! int8_linear() got an unexpected keyword argument 'input_act_weight'
[ERROR] Traceback (most recent call last):
  File "C:\Comfy037_images\ComfyUI_windows_portable\ComfyUI\execution.py", line 547, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy037_images\ComfyUI_windows_portable\ComfyUI\execution.py", line 352, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy037_images\ComfyUI_windows_portable\ComfyUI\execution.py", line 326, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Comfy037_images\ComfyUI_windows_portable\ComfyUI\execution.py", line 314, in process_inputs
    result = f(**inputs)
  File "C:\Comfy037_images\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-svdint4\comfyui_turing_utils\nodes\loaders.py", line 71, in load_diffusion_model
    service.load_convrot_model(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        model_path,
        ^^^^^^^^^^^
        force_int8_gemm,
        ^^^^^^^^^^^^^^^^
        attention_backend=patch_attention,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Comfy037_images\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-svdint4\comfyui_turing_utils\loading\convrot.py", line 152, in load_convrot_model
    prepare_turing_runtime(expected, load_device, attention_backend)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy037_images\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-svdint4\comfyui_turing_utils\precision.py", line 148, in prepare_turing_runtime
    preflight_kitchen(device, bool(summary.w4a4), bool(summary.w8a8))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy037_images\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-svdint4\comfyui_turing_utils\quantization\dispatch.py", line 275, in preflight_kitchen
    output = comfy_kitchen.int8_linear(
        x,
    ...<4 lines>...
        convrot_groupsize=256,
    )
  File "C:\Comfy037_images\ComfyUI_windows_portable\python_embeded\Lib\site-packages\comfy_kitchen\__init__.py", line 1037, in int8_linear
    return impl(**kwargs)
TypeError: int8_linear() got an unexpected keyword argument 'input_act_weight'

[INFO] Prompt executed in 14.39 seconds

**Comment by jpetersanchex** [comment]
Same error here, same place (`dispatch.py` line 275, `preflight_kitchen`). I get it from **both** Load ConvRot DiT and Load ConvRot CLIP, since both call `prepare_turing_runtime` → `preflight_kitchen`. I traced the root cause and have a working local fix.

**Environment:** Quadro RTX 5000 (sm75), Windows 11, ComfyUI 0.37.0, comfy-kitchen 0.2.35, PyTorch 2.11.0+cu130, Python 3.13.9, comfyui-turing-utils at commit 7bc3cd8.

**Root cause:** starting with **comfy-kitchen 0.2.34**, the public `comfy_kitchen.int8_linear()` always forwards four new kwargs to the selected backend implementation, even when they are `None`: `input_act_weight`, `input_act_eps`, `residual`, `residual_scale`. The plugin's registered backend `int8_linear` in `quantization/dispatch.py` does not declare them, so every call fails. (0.2.33 does not forward them.) Downgrading is not a clean option because ComfyUI 0.37.0 pins `comfy-kitchen==0.2.35` in requirements.txt.

**Local fix that works for me:** add the four parameters to the signature and delegate to `kitchen_cuda.int8_linear` whenever they are actually used, so layers requesting `rms_norm` or a fused residual are not silently computed wrong:

    def int8_linear(
        x, weight, weight_scale, bias=None, out_dtype=None,
        convrot=False, convrot_groupsize=256, input_act=None,
        input_act_weight=None, input_act_eps=0.0,
        residual=None, residual_scale=None,
        output=None,
    ):
        ...
        kitchen_extra = {}
        if input_act_weight is not None or input_act == "rms_norm":
            kitchen_extra["input_act_weight"] = input_act_weight
            kitchen_extra["input_act_eps"] = input_act_eps
        if residual is not None:
            kitchen_extra["residual"] = residual
            kitchen_extra["residual_scale"] = residual_scale

        if (kitchen_extra or x.dtype not in (torch.bfloat16, torch.float16) or ...):
            result = kitchen_cuda.int8_linear(..., input_act=input_act, **kitchen_extra)

**Result with the fix** (Qwen-Image-2.1 edit, 25 steps, 896×1152, 2 references):
- `Loaded ConvRot model ... W8A8=192` and `dense=w8a8 via bundled_turing_w8a8 native=True`
- KSampler: **5.6–6.5 s/it** with ConvRot DiT vs **29 s/it** with the BF16 checkpoint on the stock UNETLoader.

@zpc-git until there's an official fix, this change to `dispatch.py` should unblock you too.

Thanks for the plugin, it's a big speedup on Turing.

**Comment by zpc-git** [comment]
@[jpetersanchex](https://github.com/jpetersanchex)
jpetersanchex

Thanks for the fix man, 

--------------------------went from 1min 40------------------------------------------------

[INFO] got prompt
[INFO] Model storage policy: fast_disk=True paths=['C:\\Comfy037_images\\ComfyUI_windows_portable\\ComfyUI\\models\\vae\\qwen_image_2.1_vae_bf16.safetensors']
[INFO] Using pytorch attention in VAE
[INFO] Using pytorch attention in VAE
[INFO] VAE load device: cuda:0, offload device: cpu, dtype: torch.float16
[INFO] Found quantization metadata version 1
[INFO] Using MixedPrecisionOps for text encoder
[INFO] Model storage policy: fast_disk=True paths=['C:\\Comfy037_images\\ComfyUI_windows_portable\\ComfyUI\\models\\text_encoders\\qwen3vl_8b_int8_convrot.safetensors']
[INFO] CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
[INFO] Requested to load QwenImage21TEModel_
[INFO] Model QwenImage21TEModel_ prepared for dynamic VRAM loading. 9596MB Staged. 0 patches attached. Force pre-loaded 255 weights: 849 KB.
[INFO] Model QwenImage21TEModel_ prepared for dynamic VRAM loading. 9596MB Staged. 0 patches attached. Force pre-loaded 255 weights: 849 KB.
[INFO] Found quantization metadata version 1
[INFO] Detected mixed precision quantization
[INFO] Using mixed precision operations
[INFO] Native ops: int8_tensorwise, convrot_w4a4, asym_w4a8_int8 , emulated ops: mxfp8, float8_e4m3fn, nvfp4, float8_e5m2
[INFO] model weight dtype torch.bfloat16, manual cast: torch.float32
[INFO] model_type FLUX
[INFO] Model storage policy: fast_disk=True paths=['C:\\Comfy037_images\\ComfyUI_windows_portable\\ComfyUI\\models\\diffusion_models\\qwen_image_2.1_int8_convrot.safetensors']
[INFO] Requested to load QwenImage21
[INFO] Model QwenImage21 prepared for dynamic VRAM loading. 7179MB Staged. 0 patches attached. Force pre-loaded 65 weights: 63 KB.
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [01:28<00:00,  3.54s/it]
[INFO] Requested to load WanVAE
[INFO] 0 models unloaded.
[INFO] Model WanVAE prepared for dynamic VRAM loading. 644MB Staged. 0 patches attached. Force pre-loaded 68 weights: 102 KB.
[INFO] Prompt executed in 110.02 seconds

-------------to less than 40s---------------------------------------------------------------------------------

[INFO] Prompt executed in 38.88 seconds
[INFO] got prompt
[INFO] Model QwenImage21TEModel_ prepared for dynamic VRAM loading. 9596MB Staged. 0 patches attached. Force pre-loaded 255 weights: 849 KB.
[INFO] 0 models unloaded.
[INFO] Model QwenImage21TEModel_ prepared for dynamic VRAM loading. 9596MB Staged. 0 patches attached. Force pre-loaded 255 weights: 849 KB.
[INFO] 0 models unloaded.
[INFO] Model QwenImage21 prepared for dynamic VRAM loading. 7179MB Staged. 0 patches attached. Force pre-loaded 65 weights: 63 KB.
  0%|                                                               | 0/25 [00:00<?, ?it/s,   Model Initializing ...  ][INFO] [Turing/attention] Bundled Turing W8A8 active: device=cuda:0 dtype=torch.bfloat16 layout=NHD Q=(1, 4096, 32, 128) K=(1, 4120, 32, 128) V=(1, 4120, 32, 128) heads=32
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:32<00:00,  1.30s/it]
[INFO] 0 models unloaded.
[INFO] Model WanVAE prepared for dynamic VRAM loading. 644MB Staged. 0 patches attached. Force pre-loaded 68 weights: 102 KB.
[INFO] Prompt executed in 38.76 seconds
